added documentation for specifying multiple hosts to also-proxy
telepresenceio/telepresence pull request #1446
Opened 2020-10-04 14:20 UTC by divbhasin

Updated the "Proxying methods" section of the docs with a line specifying how to use --also-proxy with multiple hosts.

Closes #1440

2020-10-12 00:17 UTC, divbhasin commented
@ark3 can you please take a look? If it looks good, would you mind adding the `hacktoberfest-accepted` label? Thank you :)

2020-10-12 15:43 UTC, ark3 requested changes
Great work! Could you please add a similar note to `docs/reference/proxying.md`?

We have typically not mentioned documentation improvements in the changelog unless they correspond to feature changes. There are one or two notable exceptions, but I don't think this one really needs it. Could you please drop the news fragment?

Thank you for the PR!

2020-10-16 21:03 UTC, divbhasin commented
@ark3 Can you please take a look?

2020-10-23 13:11 UTC, ark3 approved these changes

2020-10-23 13:11 UTC, merged