Fixes an edge case when selecting a container by port number
telepresenceio/telepresence pull request #1927
Opened 2021-07-27 03:09 UTC by 0x6a77

## Description

This fixes an edge case when selecting a container by port number. The solution was to make the logic much clearer and easier to read.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to either submit a docs PR, or tell Matt about the necessary documentation changes.
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

2021-07-27 05:14 UTC, thallgren requested changes
Thank you very much for this fix @0x6a77. It looks good aside from my nits. After fixing them, please do the following:
1. Add a bugfix entry to `CHANGELOG.md`
2. `make format` (to get rid of the current lint error).
3. Commit with a "Sign-off" (will get rid of the DCO error).

2021-07-27 05:14 UTC, thallgren commented on pkg/install/discovery.go
> +		for ci := 0; ci < len(cns); ci++ {
```suggestion
	containerLoop:
		for ci := range cns {
```

2021-07-27 05:14 UTC, thallgren commented on pkg/install/discovery.go
> +			for ci := 0; ci < len(cns); ci++ {
```suggestion
			for ci := range cns {
```

2021-07-27 05:14 UTC, thallgren commented on pkg/install/discovery.go
> +		// If no container matched, then use the first container with no ports at all
```suggestion
		// If no container matched, then use the first container with no ports at all. This
		// enables intercepts of containers that indeed do listen a port but lack a matching
		// port description in the manifest, which is what you get if you do:
		//     kubectl create deploy my-deploy --image my-image
		//     kubectl expose deploy my-deploy --port 80 --target-port 8080
```

2021-07-27 05:14 UTC, thallgren commented on pkg/install/discovery.go
> +		for ci := 0; ci < len(cns); ci++ {
And then use `break containerLoop` instead of just `break` in the inner loop.

2021-07-27 05:15 UTC, thallgren commented on pkg/install/discovery.go
> +		for ci := 0; ci < len(cns); ci++ {
And then use break containerLoop instead of just break in the inner loop.

2021-07-27 06:25 UTC, 0x6a77 commented
that failing test doesn't seem like it's related. any ideas about what i should do to fix it?

2021-07-27 21:37 UTC, thallgren approved these changes
This looks great. Thanks. I agree that the test failure is unrelated, perhaps a temporary glitch at our download site. I've restarted that test.

2021-07-28 06:52 UTC, merged

2021-08-12 20:31 UTC, josecv commented
Hi @0x6a77, hope you are well!
Thank you for this PR. We'd like to invite you to our upcoming [meet the maintainers](https://www.getambassador.io/about-us/events/meet-the-maintainers-sessions/telepresence/081821/) event.
This will be an opportunity to chat with us and other members of the open source community, provide feedback, and ask questions on Telepresence. We will also be presenting features that were introduced to Telepresence in the past six weeks.
It will be taking place on August 18 at 10:00 AM Eastern Time.
Hope to see you there!