Josecv/iptables
telepresenceio/telepresence pull request #2088
Opened 2021-09-16 13:38 UTC by josecv

## Description

A few sentences describing the overall goals of the pull request's commits.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to either submit a docs PR, or tell Matt about the necessary documentation changes.
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.

2021-09-19 08:03 UTC, thallgren requested changes
Aside from a couple of nits, this looks really promising.

I see that the old behavior is retained when the ports are named. Is there any particular reason for that or could we use iptables there too? It might be easier to support just one solution.

2021-09-19 08:03 UTC, thallgren commented on cmd/traffic/cmd/agent/client.go
> +		level = os.Getenv(install.EnvPrefix + "LOG_LEVEL")
I think `_TEL_AGENT_LOG_LEVEL` should have precedence. The `LOG_LEVEL`, if present, is either legacy (which is weird, if combined with a new agent image), or it's a copy from the intercepted container, in which case our agent should include it in the propagated environment (which it does), but not act on it since we now have our own TP-specific setting for that.

2021-09-19 08:03 UTC, thallgren commented on cmd/traffic/logger.go
> +		level = os.Getenv(install.EnvPrefix + "LOG_LEVEL")
The `install.EnvPrefix` is `_TEL_AGENT` and specific for the agent. This code is used by both the traffic-manager and the traffic-agent. Seems weird that the traffic-manager should attempt to set its log-level from the agent. Perhaps pass the level as an argument to `doMain()` and then to `makeBaseLogger()`?

2021-09-19 08:03 UTC, thallgren commented on cmd/traffic/cmd/agent/client.go
> +		level = os.Getenv(install.EnvPrefix + "LOG_LEVEL")
The `_TEL_AGENT_LOG_LEVEL` must be included in the global `skipKeys` map.

2021-09-19 08:03 UTC, thallgren commented on pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-initializer.output.yaml
> +            runAsUser: 7777
Will this user have permissions to mount everything from the intercepted container (I know we have a ticket up claiming that this happens already when running as root and I wouldn't like to see that problem getting worse)?

2021-09-19 08:03 UTC, thallgren commented on pkg/install/container.go
> +const EnvPrefix = "_TEL_AGENT_"
This change belong in the previous commit. No need to change it though.

2021-09-19 08:03 UTC, thallgren commented on cmd/traffic/cmd/agentinit/agent_init_windows.go
> +// It really doesn't matter, since there's no support for windows-based containers of any sort, but it'll fail the build.
This shouldn't be needed (but that's for another PR). There should never be an attempt to build stuff under `cmd/traffic` on platforms other than Linux.

2021-09-19 08:03 UTC, thallgren commented on cmd/traffic/cmd/agentinit/agent_init.go
> +	return nil
Great comments in this method!

2021-09-19 08:03 UTC, thallgren commented on pkg/install/discovery.go
> +	isName := len(validName) == 0
Oh dear (blushing).

2021-09-20 13:46 UTC, josecv commented on pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-initializer.output.yaml
> +            runAsUser: 7777
That is a great question, let me go test it out

2021-09-20 14:01 UTC, josecv commented
> Is there any particular reason for that or could we use iptables there too?

There's nothing stopping us from using iptables there too --in fact when I was testing this, at one point I was using builds that only ever used iptables and they seemed to be okay. My only worry is accidentally breaking workloads that work today so IMO we should roll it out slowly and change that logic in a later release.
However, if you feel like we should just rip off the band-aid now I could also be convinced 🙂 

On a similar note, in theory this should also work to allow intercepting headless services, but when I tested that it didn't work at all --probably, some tweaking of the iptables would be necessary to get them working.

2021-09-20 14:37 UTC, josecv commented on pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-initializer.output.yaml
> +            runAsUser: 7777
So i just tried out creating something like this:
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: echo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: Service
metadata:
  name: echo-auto-inject
spec:
  type: ClusterIP
  selector:
    service: echo-auto-inject
  ports:
    - name: proxied
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-auto-inject
  labels:
    service: echo-auto-inject
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo-auto-inject
  template:
    metadata:
      annotations:
        telepresence.getambassador.io/inject-traffic-agent: enabled
      labels:
        service: echo-auto-inject
    spec:
      volumes:
        - name: echo-vol
          persistentVolumeClaim:
            claimName: echo-pvc
      securityContext:
        fsGroup: 0
      containers:
        - name: echo-auto-inject
          image: jmalloc/echo-server
          volumeMounts:
          - name: echo-vol
            mountPath: /var/echo
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
```

And then intercepting it and writing to the volume:

```bash
$ telepresence intercept echo-auto-inject --port 8080
Using Deployment echo-auto-inject
intercepted
    Intercept name    : echo-auto-inject
    State             : ACTIVE
    Workload kind     : Deployment
    Destination       : 127.0.0.1:8080
    Volume Mount Point: /var/folders/j8/kzkn41mx2wsd_ny9hrgd66fc0000gp/T/telfs-1093182516
    Intercepting      : all TCP connections

$ echo 'heyo' > /var/folders/j8/kzkn41mx2wsd_ny9hrgd66fc0000gp/T/telfs-1093182516/var/echo/fff
$ cat /var/folders/j8/kzkn41mx2wsd_ny9hrgd66fc0000gp/T/telfs-1093182516/var/echo/fff
heyo
```

It seems like it works well enough, but is there something specific I should try @thallgren?

2021-09-20 19:32 UTC, josecv commented on pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-initializer.output.yaml
> +            runAsUser: 7777
Also tried with a non-root pod security context, and it works (whereas I think it didn't use to)

2021-09-21 14:08 UTC, thallgren approved these changes

2021-09-22 14:02 UTC, merged