bugfix for empty list for --json
telepresenceio/telepresence pull request #2260
Opened 2021-12-09 16:21 UTC by njayp

Signed-off-by: njayp <nickjaypowell@gmail.com>

## Description

Earlier I added a --json flag to "telepresence list". I missed the case where there were no workloads to list. Oops.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to either submit a docs PR, or tell Matt about the necessary documentation changes.
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.

2021-12-10 20:56 UTC, donnyyung commented on CHANGELOG.md
> +- Bugfix: Fixed a bug where --json flag would not trigger for "telepresence list" for an empty list.
nit: formatting `telepresence list` 

I'd also change the messaging to say something like "Fixed a bug where `--json` flag did not output json for `telepresence list` when there were no workloads" or something like that.

2021-12-10 20:57 UTC, donnyyung requested changes
Just once change around the changelog, but other than that looks good!

2021-12-10 21:46 UTC, donnyyung approved these changes

2022-01-04 16:20 UTC, zopanix commented
@donnyyung : FYI: this will also fix #2076 2076

2022-02-10 14:27 UTC, merged