Draft of long-running daemon to test Ci-build
telepresenceio/telepresence pull request #2276
Opened 2022-01-04 17:03 UTC by thallgren

## Description

A few sentences describing the overall goals of the pull request's commits.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.

2022-01-05 21:09 UTC, josecv requested changes
this all looks good but it'd be good to discuss about session lifecycles as per my other comment

2022-01-05 21:09 UTC, josecv commented on pkg/client/daemon/service.go
> +	session       *session
is this a dupe? there's another `session *session` on line 51

2022-01-05 21:09 UTC, josecv commented on pkg/client/daemon/service.go
> +		return nil
hmm i feel like the handling of the sessions' lifecycle is a little bit awkward in general. I don't really like the context being stored in the struct here, or that successive sessions share the same context.
It's also a little hard to tell by looking at `daemon/service.go` where exactly the session's goroutines are getting started.

IMO what we should consider doing is split `newSession` into a `newSession` that doesn't start any new goroutines and a `runSession` that actually kicks everything off.
We could then have this goroutine (`g.Go("session")`) receive the `newSession` on some channel and `runSession` on it. Here's sort of what I'm picturing:

```
type service struct {
	sessionCh      chan *session
        sessionErrCh chan error
	sessionLock   sync.Mutex
	session           *session
}

func (d *service) SetOutboundInfo(ctx context.Context, info *rpc.OutboundInfo) (*empty.Empty, error) {
	d.sessionLock.Lock()
	defer d.sessionLock.Unlock()
	if d.session != nil {
		return nil, status.Error(codes.AlreadyExists, "an active session exists")
	}
	s, err := newSession(ctx, d.scout, info)
	if err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	d.sessionCh <- s
        err = <-d.sessionErrCh
        // handle err
        d.session = s // session was started successfully, so store it
	return &empty.Empty{}, nil
}

g.Go("session", func(c context.Context) (err error) {
      c, d.cancel = context.WithCancel(c)
      for {
          sess := <-d.sessionCh
          sCtx, sCancel := context.WithCancel(c)
          doneCh, err := sess.runSession(sCtx)
          d.sessionErrCh <- err
          select {
                case <-c.Done():
                     sCancel()
                     return nil
                case <-doneCh: // assuming doneCh is already closed if runSession failed
                     sCancel()
          }
      }
})
```

This looks a bit bulkier than what you have but i think it gives us a few advantages:

* opens it up to refactor session cancellation so that just doing `sCancel()` is good enough to stop the session -- eventually we could just store `sCancel` and call it in `disconnect`, dropping the need for `session.stop()`. This would be good because right now it's not clear to me that `d.cancel` will clean everything up correctly
* makes it really clear that the sessions are running in the "session" goroutine
* prevents the sessions' context from being shared by multiple sessions, or leaked to the rest of this struct

2022-01-05 22:32 UTC, thallgren commented on pkg/client/daemon/service.go
> +	session       *session
Not sure what's going on here. Must be a glitch in how the diff is displayed somehow. There's only one session in the struct and that's the one below the `sessionsLock`.

2022-01-05 23:01 UTC, thallgren commented on pkg/client/daemon/service.go
> +		return nil
Not sure I understand your reasoning here. The correspondence to your `sCancel` is currently stored as `cancel` in the `session` struct. It's created by the `newSession` function from the parent `ctx` which is the `d.sessionsCtx`.  A `disconnect` calls `d.session.stop` to do necessary clean-up. That method in turn calls that `cancel` and terminates the session.

How would `disconnect` get hold of the `sCancel`? It needs to be stored somewhere. What place is better than the session that it cancels?

Please note that the `ctx` received by `Connect` is short lived. Using that context would terminate the connection as soon as the connect call returns.  Hence the need for the `d.sessionsCtx` which lives until the process terminates.

2022-01-05 23:02 UTC, thallgren commented on pkg/client/daemon/service.go
> +		return nil
`Connect` in my reasoning is `SetOutboundInfo` before it was renamed.

2022-01-06 06:41 UTC, thallgren commented on pkg/client/daemon/service.go
> +		return nil
Your design is cleaner so I decided to go ahead and implement something similar. The new design is based on your channel pair and moving the actual session execution into the "session" goroutine. It differs slightly in how the cancellation is handled but there's no explicit call to `stop` now. The session can only be cancelled by calling its `cancel` (which is the context cancellation method).

2022-01-06 14:40 UTC, josecv approved these changes

2022-01-07 15:50 UTC, merged