add "how it works" and "tools" sections
telepresenceio/telepresence pull request #2548
Opened 2022-04-25 23:03 UTC by raphaelreyna

## Description

A few sentences describing the overall goals of the pull request's commits.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2022-04-26 04:35 UTC, thallgren requested changes

2022-04-26 04:35 UTC, thallgren commented on README.md
> + 3. Creates a virtual network device called a _TUN device_ and names it `tel0`.
The device is named `tun0` on macOS (or `tun1`, `tun2`, etc. whichever is available) so using "tel0" in the text can be confusing for a Mac user.

2022-04-26 04:35 UTC, thallgren commented on README.md
> +Telepresence is on the other side of `tel0` and picks up the packets, injecting them into the cluster through a gRPC connection with Traffic Manager.
The packets aren't really "injected". The data of the packages are tunneled over a stream (in packets that are much larger than the TCP packets). I suggest you use different wording here unless you want to go into detail on how that works. How about "The operating system then sees that the address is covered by one of the TUN device's subnets, which means that telepresence will route the traffic to the cluster through a gRPC connection with the Traffic Manager"?

2022-06-23 08:38 UTC, thallgren commented
@raphaelreyna can you please rebase and update this one so that we can merge it?

2022-08-25 15:46 UTC, DanielYWoo commented
could you also put some explanation about the DNS? How the domain names are resolved by coreDNS?

2024-06-20 09:17 UTC, merged