Add --output global flag
telepresenceio/telepresence pull request #2561
Opened 2022-05-05 22:42 UTC by raphaelreyna

Signed-off-by: Raphael Reyna <raphaelreyna@protonmail.com>

## Description

Allows for structured output. 
If enabled, the output of the subcommand is wrapped in a JSON object along with the subcommand name and an error if it was returned.
Doesn't interfere with subcommands that already have a `--json` flag by treating their output as a `json.RawMessage` type rather than a string type.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2022-05-05 22:44 UTC, raphaelreyna commented
For subcommands that already have a `--json` flag, should enabling json output globally automatically set the subcommand's `--json` flag as well?

2022-05-06 14:00 UTC, thallgren requested changes
Looks good overall. Just a couple of nits.

2022-05-06 14:00 UTC, thallgren commented on pkg/client/cli/util.go
> +	switch o.nativeJSON {
Seems a bit overkill to use a switch on a boolean. I suggest you use if/else instead.

2022-05-06 14:00 UTC, thallgren commented on pkg/client/cli/util.go
> +		json.NewEncoder(w).Encode(x)
You must explicitly ignore the return using `_ = ...`.

2022-05-06 14:00 UTC, thallgren commented on pkg/client/cli/util.go
> +type Output struct {
Does this type need to be exported?

2022-05-06 16:28 UTC, raphaelreyna commented on pkg/client/cli/util.go
> +		json.NewEncoder(w).Encode(x)
Ah ok, I was thinking of adding an annotation for the linter since this will never produce an error but this is cleaner.

2022-05-06 16:30 UTC, raphaelreyna commented on pkg/client/cli/util.go
> +type Output struct {
Not sure yet...
I might end up importing into the `cliutil` package since its writing straight to stdout and we want to intercept that.

2022-05-07 20:44 UTC, thallgren requested changes, later dismissed

2022-05-07 20:44 UTC, thallgren commented on pkg/client/cli/output/output.go
> +func Outputs(ctx context.Context) (stdout, stderr io.Writer) {
The move into an `output` package introduces stuttering, `output.Outputs`. Consider changing the `Outputs` to something that would be more suitable when prefixed with `output`. Perhaps `output.Formatted` ?

2022-05-07 20:44 UTC, thallgren commented on pkg/client/cli/output/output_test.go
> +		cmd.LocalFlags().Set("json", "true")
It's often helpful to run `make lint` before you commit ;-)

2022-05-10 20:11 UTC, josecv approved these changes

2022-05-10 20:11 UTC, merged