add --watch option to `tele list`
telepresenceio/telepresence pull request #2600
Opened 2022-05-19 21:10 UTC by njayp

Signed-off-by: njayp <nickjaypowell@gmail.com>

## Description

A `WatchWorkloads` grpc already exists, i add a flag in `tele list` that uses it.

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2022-05-19 21:35 UTC, raphaelreyna reviewed
This might cause some issues with the global `--output` flag since it buffers prints to stdout when output json. 
Perhaps check if that global flag is set to `json` and if so return an error or just set the local `--json` flag?

2022-05-20 00:11 UTC, njayp commented
so i understand better, what issues would it cause?

2022-05-20 02:10 UTC, raphaelreyna commented
> so i understand better, what issues would it cause?

When the `--output=json` flag is set, the `io.Writer` returned by `cmd.OutOrStdout()` is not backed by `os.Stdout` but by a ` `strings.Builder` which is then used to form the json response that is flushed to `os.Stdout` _after_ the command exits.
Basically, it prevents any sort of "streaming" output.

2022-05-20 05:55 UTC, thallgren requested changes
Looks good overall. Perhaps add an integration test to verify the functionality?

2022-05-20 05:55 UTC, thallgren commented on pkg/client/cli/cmd_list.go
> +	if len(workloads) == 0 {
Nit, but shouldn't this test be the very first thing that happens in the function?

2022-05-20 05:55 UTC, thallgren commented on pkg/client/cli/cmd_list.go
> +		*/
Please remove this comment, or explain why it's there.

2022-05-20 13:53 UTC, njayp commented
> I can see how the term "snapshot" makes sense for a watcher that delivers snapshots, but it's a bit far fetched as an option for a list command.
> 
> * What's the difference when you list with or without a `--snapshot`?
> * When you use `--snapshot` you get JSON output.
> * Oh? I though I'd get that with the global `--json` flag?
> * Yeah, you will, but that's different, because <fill in explanation here>.

My thinking was `--output json` gets you what you usually get, but in a json obj. `--snapshot` gets you the full snapshot object. Both gets you the snapshot object in your json object

2022-05-20 13:57 UTC, thallgren commented
@njayp "Both gets you the snapshot object in your json object" sounds like the `--snapshot` option is redundant, which I think it somehow isn't?

2022-05-20 14:00 UTC, njayp commented
> @njayp "Both gets you the snapshot object in your json object" sounds like the `--snapshot` option is redundant, which I think it somehow isn't?

its not redundant because errors. without the `--output json` flag set, errors are not in json format

2022-05-20 14:03 UTC, thallgren commented
Ok? And that's an distinction that is important enough to introduce this somewhat confusing flag?

2022-05-20 14:14 UTC, njayp commented
> Ok? And that's an distinction that is important enough to introduce this somewhat confusing flag?

i need json errors for docker. what we could do is detect if `--output json` is set, and if it is, print the snapshot object in the json object. This would remove the ability to output the human-readable list in a json object, but maybe that isn't a common use-case. Is this what you would prefer?

2022-05-20 14:16 UTC, thallgren commented
Ok, so why don't we change the `--json` flag to give us JSON errors then? @raphaelreyna would that be hard to do?

2022-05-20 14:17 UTC, thallgren commented
What I don't want is different ways of telling a command to produce JSON output, motivated needs that our users rarely know anything about.

2022-05-20 14:18 UTC, njayp commented
> Ok, so why don't we change the `--json` flag to give us JSON errors then? @raphaelreyna would that be hard to do?

I am against having multiple json flags floating around, imo having `--json` and `--output json` have different behavior is the most confusing

2022-05-20 14:34 UTC, thallgren commented
I totally agree. I think we should have one single way of asking for JSON output. The only viable use-case for it is when the CLI is called from another process, and when that happens, surely both output and errors must be returned as JSON.

2022-05-21 05:56 UTC, thallgren commented
Something weird happened in PR #2602. It contains a whole slew of commits that doesn't belong to it and that affects the change-set of this PR (surely it doesn't span 32 files?). Some rebasing is needed in order to see what's included here.

2022-06-02 14:15 UTC, thallgren approved these changes

2022-06-02 17:58 UTC, merged