[WIP]  feat: allow ignore volume mounts during injection
telepresenceio/telepresence pull request #2665
Opened 2022-06-23 22:01 UTC by kolorful

## Description

Allow users to set annotation `telepresence.getambassador.io/ignore-volume-mounts: "foo,bar"` to instruct the mutating webhook to ignore certain volume mounts to "be copied" during injection. 

This WIP PR is currently more of a proposal or PoC to address an issue discovered in https://github.com/telepresenceio/telepresence/issues/2596#issuecomment-1164617536

Our application unfortunately has a host path mount on `/var/xyz/spam` (xyz owned by root and spam owned by 1001). When it gets mounted by the agent sidecar and all the symlinks in place, `/tel_app_mounts/app/var` becomes owned by root, and hence cause error why the sidecar tries to `mkdir /tel_app_mounts/app/var/run`
```
ls -la /tel_app_exports/app
lrwxrwxrwx    1 1001     1001            24 Jun 23 16:00 var -> /tel_app_mounts/app/var

ls -la /tel_app_mounts/app/var
drwxr-xr-x    3 root     root          4096 Jun 23 16:15 .
drwxr-xr-x    3 root     root          4096 Jun 23 16:15 xyz
``` 
I wonder if this is actually a proper fix or there is other alternatives (we don't really want to manually generate the yamls).

Thanks!

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2022-06-24 07:09 UTC, thallgren commented
Thanks for providing this PR. It highlights a generic problem in how the traffic-agent propagates the mounts. It doesn't solve that problem, but there might be other reasons for preventing a remote volume mount selectively, so your addition has value regardless.

A proper fix must detect that there are several things to mount under `/var` and instead create that as a directory, and then symlink from there, so you'd get:
```
ls -la /tel_app_exports/app
drwxr-xr-x    3 1001     1001          4096 Jun 23 16:15 .
drwxr-xr-x    3 1001     1001          4096 Jun 23 16:15 var

ls -la /tel_app_exports/app/var
drwxr-xr-x    3 root     root          4096 Jun 23 16:15 .
lrwxrwxrwx    1 1001     1001            24 Jun 23 16:00 xyz -> /tel_app_mounts/app/var/xyz
lrwxrwxrwx    1 1001     1001            24 Jun 23 16:00 run -> /tel_app_mounts/app/var/run

ls -la /tel_app_mounts/app/var/xyz
drwxr-xr-x    3 root     root          4096 Jun 23 16:15 .
drwxr-xr-x    3 root     root          4096 Jun 23 16:15 spam
```
If you want to proceed with your PR as it stands now, I'd approve that. If you want to give the proper fix a try, that'd be great too. In any case, you must make sure that your commits are signed (DCO tests currently fail), and add an entry to the CHANGELOG.md.

2022-06-24 21:45 UTC, kolorful commented
@thallgren thank you for the encouraging feedback! I have tested and verified the functionality in our testing clusters.

I've renamed the annotation to `telepresence.getambassador.io/inject-ignore-volume-mounts`, so it's consistent with [other injector related annotations](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config/#service-name-and-port-annotations).

2022-06-27 13:58 UTC, kolorful commented
@thallgren would you mind take a look this PR when you have time, I can't post in datawire-oss slack cause I can't register with my email. Thanks!

2022-06-27 14:20 UTC, thallgren requested changes
Just some minor stuff. Looks good overall.

2022-06-27 14:20 UTC, thallgren commented on pkg/agentconfig/container.go
> +		ivms[vm] = true
```suggestion
		ivms[strings.TrimSpace(vm)] = true
```
because it's not unlikely that a user will use comma and space to separate the entries.

2022-06-27 14:20 UTC, thallgren commented on pkg/agentconfig/container.go
> +	ivms := make(map[string]bool, len(vmSlice))
A bit of a nit-pick, and I'm fine if you leave it as is, but the usage for `ivms` is a unique set of strings. This gives the impression that it's a map of `true` or `false` values. I usually use `map[string]struct{}` (and `if _, ok = ignoredVolumeMounts[m_name]; ok {` on line 194) to make sure it's understood that the value is insignificant.

2022-06-27 14:26 UTC, thallgren commented
@kolorful What link are you using when trying to register with Slack? It should be https://datawire-oss.slack.com/

2022-06-27 15:34 UTC, kolorful commented
> @kolorful What link are you using when trying to register with Slack? It should be https://datawire-oss.slack.com/

I used the link in this page:  https://datawire-oss.slack.com/signup#/domain-signup, but my email is not in the allowed domain list.

2022-06-27 15:34 UTC, kolorful commented
> Just some minor stuff. Looks good overall.

Thanks for reviewing, all updated.

2022-06-27 15:35 UTC, thallgren approved these changes

2022-06-27 17:13 UTC, kolorful commented
One of the test failed but it doesn't seem to be related to my change?

2022-06-27 21:16 UTC, thallgren commented
I restarted that test. Regarding slack, try this link instead: http://a8r.io/slack.

2022-06-28 14:09 UTC, merged