feat(chart): support livenessProbe and readinessProbe
telepresenceio/telepresence pull request #2877
Opened 2022-11-10 10:41 UTC by maxime1907

## Description

Adds a livenessProbe and readinessProbe so that it restarts the pod if it hangs up for whatever reason

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [x] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2022-11-12 04:22 UTC, thallgren requested changes
Thanks for providing this. It looks besides my comment about the changelog.

You'll need to sign off on the commit to pass our DCO check.

2022-11-12 04:22 UTC, thallgren commented on charts/telepresence/CHANGELOG.md
> +
This must be moved to the CHANGELOG.md at the repository root. Also, please make the entry more verbose. Where is it added? For what purpose? What pod is it for?

The CHANGELOG.md here is no longer maintained (and yes, we should remove it).

2022-11-15 09:25 UTC, maxime1907 commented on charts/telepresence/CHANGELOG.md
> +
okay thanks for the review, i have done the changes!

2022-11-15 09:26 UTC, maxime1907 commented
> Thanks for providing this. It looks besides my comment about the changelog.
> 
> You'll need to sign off on the commit to pass our DCO check.

thanks for the review, it should be good now!

2022-11-17 02:41 UTC, thallgren approved these changes

2022-11-17 02:41 UTC, merged