Added timeouts config `agentArrival`
telepresenceio/telepresence pull request #3148
Opened 2023-04-24 16:40 UTC by xzhang-brex

## Description

Currently, the time to wait for the agent to arrive is hardcoded 30 seconds, however, it is not sufficient for some slow pods. Here we add `agentArrival` to the client config to tell the traffic manager how long it should wait for the agent to arrive.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.md`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2023-04-24 16:48 UTC, xzhang-brex commented on CHANGELOG.md
> -  docker run directly from a docker context.
typo fix that is unrelated to the subject of this PR.

2023-04-24 16:48 UTC, xzhang-brex commented on pkg/client/config.go
> -	// PrivateTrafficManagerConnect is how long to wait for the traffic-manager API to connect
typo fix that is unrelated to the subject of this PR.

2023-04-25 11:13 UTC, thallgren requested changes
Thanks @xzhang-brex for this PR. It's well made. I do however think that the config ended up in the wrong place, which is my fault. I didn't have time to go through this with you in depth.

The `config.yml` file and it's settings are intended for the client. The traffic-manager must be configured using the Helm chart, and values in charts/telepresence/values.yaml. A value like this would typically be configured there and then passed in via an environment variable setting. The [InterceptDisableGlobal](https://github.com/telepresenceio/telepresence/blob/release/v2/cmd/traffic/cmd/manager/managerutil/envconfig.go#L43) can serve as a good example. It is passed in as the [INTERCEPT_DISABLE_GLOBAL](https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/templates/deployment.yaml#L80) env, and originally set [here](https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/templates/deployment.yaml#L80). I think the `agentArrivalTimeout` value should be placed adjacent to the `disableGlobal` (and hence become `intecept.agentArrivalTimeout`.

Again, sorry for not providing enough info around this.

2023-04-27 04:20 UTC, xzhang-brex commented
@thallgren Thank you for the feedback! I've addressed the comment!

2023-04-27 10:08 UTC, thallgren approved these changes
Perfect! Thanks.

2023-04-27 10:10 UTC, thallgren commented on charts/telepresence/values.yaml
> +  agentArrival: 30s
This should be added to the README.md in this folder that contains a description of all values.

2023-05-01 16:02 UTC, merged