fix(chart): specify port in hook urls
telepresenceio/telepresence pull request #3161
Opened 2023-05-05 10:50 UTC by maxime1907

## Description

Specify port in hook URLs when we want to use a different port with `agentInjector.webhook.port`

## Checklist

 - [x] I made sure to update `./CHANGELOG.md`.
 - [x] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2023-05-05 15:07 UTC, thallgren requested changes
We have a `.Values.agentInjector.webhook.port` setting. Shouldn't that be used here instead of introducing a new value?

2023-05-05 15:42 UTC, maxime1907 commented
> We have a `.Values.agentInjector.webhook.port` setting. Shouldn't that be used here instead of introducing a new value?

Ah yes my bad i meant to use this value, it should be good now!

2023-05-15 12:57 UTC, thallgren approved these changes

2023-05-15 14:56 UTC, merged

2023-05-15 14:57 UTC, thallgren commented
Thanks @maxime1907 for your contribution!