Knlambert/add consumption
telepresenceio/telepresence pull request #3273
Opened 2023-07-21 18:20 UTC by knlambert

## Description

A few sentences describing the overall goals of the pull request's commits.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.yml`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2023-07-26 15:24 UTC, jacoblbeck approved these changes

2023-07-28 14:43 UTC, josecv requested changes
concerned about the performance implications of this; i suggest you just hit it a few times with [wrk](https://github.com/wg/wrk) to make sure it's all okay

2023-07-28 14:43 UTC, josecv commented on cmd/traffic/cmd/manager/state/state.go
> +		s.unlockedRemoveSessionConsumption(sessionID)
can we move this check into the method? it seems confusing to have one check in one file and another in another, if I'm looking at consumption.go I'm wondering why `Refresh` needs a client session but `unlockedRemove` doesn't

2023-07-28 14:43 UTC, josecv commented on cmd/traffic/cmd/manager/state/consumption.go
> +			sc.closeChannels()
should we like defer this? i'm concerned there's a channel leak here if you just close the one, and `closeChannels` is v easy to make idempotent

2023-07-28 14:43 UTC, josecv commented on pkg/tunnel/bidipipe.go
> +		// p.pm collects metrics only for one stream (since the same data is going through both streams)
p.pm?

2023-07-28 14:43 UTC, josecv commented on pkg/tunnel/stream.go
> +				b <- uint64(len(m.Payload()))
This is a potentially blocking channel write in the middle of hot network code, you should probably have a timeout (millis or nanos) of some sort here just in case

2023-07-28 14:43 UTC, josecv commented on cmd/traffic/cmd/manager/state/consumption.go
> +		ToClientBytesChan:   make(chan uint64),
please buffer these channels to at least 1024 messages. There's one write to the channels for every network packet that we see, which could potentially block really really badly.

2023-07-28 14:44 UTC, josecv commented
Also I think from a design perspective I'd feel much better if the channels were private and you just had methods to report one packet.

2023-07-31 14:09 UTC, josecv approved these changes
just that lock question -- if it doesn't need a lock just explain why and merge it :)

2023-07-31 14:09 UTC, josecv commented on pkg/tunnel/probe.go
> +			p.value += b
is this thread safe with GetValue? should it be locked or atomic?

2023-07-31 18:20 UTC, knlambert commented on pkg/tunnel/probe.go
> +			p.value += b
Mmh, no you're right. 

I mean, it's not really an issue in this case if the counter isn't perfectly synchronized, but it's still a race condition. I'll fix it :)

2023-07-31 20:31 UTC, merged