Remove docker scout message when pulling a docker image
telepresenceio/telepresence pull request #3290
Opened 2023-08-03 15:47 UTC by shepz

## Description

A few sentences describing the overall goals of the pull request's commits.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.yml`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2023-08-03 16:05 UTC, knlambert requested changes

2023-08-03 16:05 UTC, knlambert commented on pkg/client/docker/image.go
> +		fmt.Println(stderr.String())
```suggestion
		fmt.Fprintln(dos.Stderr, stderr.String())
```

2023-08-04 15:04 UTC, knlambert approved these changes

2023-08-04 15:04 UTC, knlambert commented on pkg/client/docker/image.go
> +		fmt.Fprintln(os.Stderr, stderr.String())
```suggestion
		fmt.Fprintln(os.Stderr, stderr.String())
```
Are you sure you need the ln though ?

2023-08-07 14:30 UTC, josecv approved these changes

2023-08-07 15:00 UTC, merged