Inject SecurityContext into traffic agent
telepresenceio/telepresence pull request #3334
Opened 2023-09-01 20:43 UTC by shepz

## Description

This PR fix the openshift CFI issue.

SCCs are defined on the SAs that run the pods. OpenShift will set the SecurityContext when you deploy the pod, using the SecurityContext from the existing container authorizes the agent injection.

## Checklist

 - [ ] I made sure to update `./CHANGELOG.yml`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `DEVELOPING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [ ] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2023-09-06 14:07 UTC, josecv approved these changes

2023-09-06 19:08 UTC, josecv approved these changes

2023-09-07 02:54 UTC, thallgren commented on pkg/agentconfig/container.go
> +				break
```suggestion
				}
				break outerLoop
```

2023-09-07 02:56 UTC, thallgren requested changes
Looks good to me.

2023-09-07 02:59 UTC, thallgren approved these changes

2023-09-07 10:58 UTC, jcornick-alabs commented
@shepz, it looks like this is all green, lets's get the RC cut as soon as possible today so we can get it to AmDocs.  We would love for them to have been able to try it before their regular meeting tomorrow.

Thanks!!

2023-09-07 12:36 UTC, merged