Add governance
telepresenceio/telepresence pull request #3391
Opened 2023-10-19 18:08 UTC by knlambert

## Description

See https://github.com/cncf/tag-contributor-strategy/issues/427.

Waiting after @cindymullins-dw to create the missing slack channels. Feel free to comment to improve this.

2023-10-19 18:13 UTC, njayp approved these changes

2023-10-20 09:04 UTC, thallgren commented on MAINTAINERS.md
> +* Sarabraj Singh, [sarabrajsingh](https://github.com/sarabrajsingh), <rsingh@datawire.io>
The heading states "alphabetical order", so this list must be reordered.

2023-10-20 09:08 UTC, thallgren requested changes
Please also remove the old GOVERNANCE.md

2023-10-20 09:08 UTC, thallgren commented on MAINTAINERS.md
> +* Sarabraj Singh, [sarabrajsingh](https://github.com/sarabrajsingh), <rsingh@datawire.io>
The heading states "alphabetical order", so this list must be reordered.
```suggestion
* Thomas Hallgren, [thallgren](https://github.com/thallgren), <thomas@datawire.io>
* Kévin Lambert, [knlambert](https://github.com/knlambert), <klambert@datawire.io>
* Nick Powell, [njayp](https://github.com/njayp), <nickpowell@datawire.io>
* Sarabraj Singh, [sarabrajsingh](https://github.com/sarabrajsingh), <rsingh@datawire.io>
* Guillaume Veschambre, [shepz](https://github.com/shepz), <gveschambre@datawire.io>
```

2023-10-20 14:25 UTC, sarabrajsingh approved these changes

2023-10-23 09:18 UTC, thallgren approved these changes

2023-10-23 09:20 UTC, thallgren commented
Consider using last name for alphabetic order (as per my proposal). I think it's far more common.

2023-10-24 13:30 UTC, josecv approved these changes

2023-10-25 14:30 UTC, shepz approved these changes

2023-10-26 19:43 UTC, merged