Use traffic-agent port-forwards for outbound and intercepted traffic
telepresenceio/telepresence pull request #3409
Opened 2023-10-31 23:15 UTC by thallgren

Use traffic-agent port-forwards for outbound and intercepted traffic.

The telepresence TUN-device is now capable of establishing direct port-forwards to a traffic-agent in the connected namespace. That port-forward is then used for all outbound traffic to the device, and also for all traffic that arrives from intercepted workloads. Getting rid of the extra hop via the traffic-manager improves performance and reduces the load on the traffic-manager. The feature can only be used if the client has Kubernetes port-forward permissions to the connected namespace. It can be disabled by setting `cluster.agentPortForward` to `false` in `config.yml`.

2023-11-01 16:44 UTC, josecv requested changes
mainly the prometheus counters

2023-11-01 16:44 UTC, josecv commented on cmd/traffic/cmd/manager/manager.go
> +	newGaugeFunc("tunnel_egress_bytes", "Number bytes tunneled to clients", s.state.CountTunnelEgress)
these should be counters since they only go up. There are different promql semantics for gauges and counters, and we wanna make sure we're doing what's standard

2023-11-01 16:44 UTC, josecv commented on cmd/traffic/cmd/manager/service.go
> +	intercepted := func(name, namespace string) bool {
can we call this `isIntercepted` please?

2023-11-01 16:44 UTC, josecv commented on cmd/traffic/cmd/agent/server.go
> +	}()
could we kick off this goroutine when we instantiate the state and then talk to it through a channel? that way we're not creating a new goroutine here for every single request. If you give the channel a big old buffer and then just do a select with a default to write to it then it won't ever block

2023-11-01 20:30 UTC, thallgren commented on cmd/traffic/cmd/agent/server.go
> +	}()
This function is called once of when a channel closes and is supposed to be very short-lived. The go routine is not strictly necessary. I just didn't want things to wait for the traffic-manager to accept the metrics. I'd like to keep it as is.

2023-11-01 20:35 UTC, thallgren commented on cmd/traffic/cmd/manager/manager.go
> +	newGaugeFunc("tunnel_egress_bytes", "Number bytes tunneled to clients", s.state.CountTunnelEgress)
I guess that goes for all of them, not just the ones I added here?

2023-11-01 20:58 UTC, thallgren commented
@josecv only the last two commits were added after your review. The rest is a rebase on top of release/v2.

2023-11-02 10:10 UTC, njayp approved these changes

2023-11-02 10:10 UTC, njayp commented on cmd/traffic/cmd/manager/service.go
> +		}
should there be a `case <-ctx.Done()` here?

2023-11-02 12:49 UTC, thallgren commented on cmd/traffic/cmd/manager/service.go
> +		}
I don't think that's necessary given that both the `agentsCh` and `interceptsCh` will be closed as soon as the context is cancelled. We don't look for `<-ctx.Done()` in `WatchAgents` and `WatchAgentsNS` either, for the same reason.

2023-11-02 13:21 UTC, josecv approved these changes

2023-11-02 17:21 UTC, merged