fix(chart): add option to disable the webhook
telepresenceio/telepresence pull request #3565
Opened 2024-04-04 13:13 UTC by capuche2412

## Description

In my use case of telepresence, the mutating webhook is not needed. To stick to the kiss programming principle, I would like to add an option to disable the webhook.

## Checklist

 - [x] I made sure to update `./CHANGELOG.yml`.
 - [x] I made sure to add any docs changes required for my change (including release notes).
 - [x] My change is adequately tested.
 - [x] I updated `DEVELOPING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [x] I updated `TELEMETRY.md` if I added, changed, or removed a metric name.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2024-04-05 06:50 UTC, thallgren requested changes
This looks promising, and I like the idea of being able to completely disable the webhook.

I think there must be some additional logic in cmd/traffic/cmd/manager/manager.go that disables the agent-injector http-service from starting (line 139), and prevents the creation of the `injectorCertGetter` (line 118)  because it will otherwise
make attempts to either watch or mount the mutator-webhook-tls secret, which is no longer generated.

2024-05-04 17:06 UTC, thallgren commented
@capuche2412 I didn't hear back from you so I decided to use your commit as the base for a more elaborated change that is in line with what I requested. Thanks for contributing and sparking this improvement.

2024-05-04 17:10 UTC, thallgren approved these changes

2024-05-05 03:22 UTC, merged

2024-05-13 08:06 UTC, capuche2412 commented
This looks amazing ! I was busy and I haven't found the time to complete this PR. 
Thanks a lot for this improvement :+1: