Lift requirement of .Release.Name == traffic-manager
telepresenceio/telepresence pull request #3737
Opened 2024-12-02 16:18 UTC by dansimone

## Description

Addresses https://github.com/telepresenceio/telepresence/issues/3731, which is an apparently unnecessary restriction that the .Release.Name under which telepresence is installed is called "traffic-manager".  This restriction was preventing telepresence from being included as a sub-chart in a parent chart called anything but "traffic-manager".

This change just does the same for "traffic-manager.name" that we already do [here](https://github.com/telepresenceio/telepresence/compare/release/v2...dansimone:telepresence:release/v2?expand=1#diff-4df592d4dba16f53e48009e7161d000c794bbdf00e385406a2e491fa8ac6b956L4) for "telepresence.name": it has a default value, but can otherwise be controlled by the `nameOverride` value.

The rest of the Helm chart is already not referring to the literal "Release.Name" in any meaningful way - everything meaningful is referring to the "traffic-manager.name".

## Checklist

 - [ ] I made sure to update `./CHANGELOG.yml`.
 - [ ] I made sure to add any docs changes required for my change (including release notes).
 - [ ] My change is adequately tested.
 - [ ] I updated `CONTRIBUTING.md` with any special dev tricks I had to use to work on this code efficiently.
 - [ ] Once my PR is ready to have integration tests ran, I posted the PR in #telepresence-dev in the datawire-oss slack so that the "ok to test" label can be applied.

2024-12-02 21:57 UTC, thallgren requested changes
Thanks for providing this.

I think this PR needs more work, because if I read it correctly, it doesn't just lift the restriction on the ReleaseName, it will also allow the actual kubernetes service to be named something other than "traffic-manager". This is problematic, because both client and the traffic-agent will use the service name "traffic-manager" verbatim in multiple places in the code when establishing gRPC connections.

I think the simple solution would be to let the service name stay fixed at "traffic-manager" (perhaps also the deployment and container name), but an improvement where the code is rewritten to instead use a selector matching the labels would be a very good addition

Did you test this PR with another name and managed to connect?

2024-12-02 22:34 UTC, dansimone commented
Good point, you're right.  Let me test out a simpler solution tomorrow, basically just what you said: just keep the traffic-manager.name hard-coded to "traffic-manager", and removing the reference the Release.Name (which I don't think has any bearing otherwise).

The following could be a way to address the hard-coding overall:
1) Merge the above simple fix
2) Update the actual code to use a selector instead of looking for a hard-coded "traffic-manager" service.  I am up for helping with this fix as well.

2024-12-03 15:34 UTC, dansimone commented
Ok, updated with the simpler solution for 1).  With this, I can install Telepresence and connect to it using the primary Helm chart or through a parent chart with an arbitrary name.

2024-12-03 20:44 UTC, thallgren approved these changes
Looks great. Thanks.

2024-12-04 08:43 UTC, merged